import {Game} from "../models/game";
export const mockGames: Game[] = [
  {
    id: 1,
    title: "The Witcher 3: Wild Hunt",
    rating: "9.8",
    imageUrl: "https://fastly.picsum.photos/id/61/3264/2448.jpg?hmac=Xi3Kq99U5tueFi0aajgUP0yWAL4xwCHg5ZXGZRLTqyI",
    description: "Embark on a thrilling open-world RPG adventure as Geralt of Rivia.",
    price: 29.99,
    releaseDate: "May 19, 2015",
    publisher: "CD Projekt",
    consoles: ["PlayStation 4", "Xbox One", "Nintendo Switch"],
  },
  {
    id: 2,
    title: "Red Dead Redemption 2",
    rating: "9.7",
    imageUrl: "https://fastly.picsum.photos/id/61/3264/2448.jpg?hmac=Xi3Kq99U5tueFi0aajgUP0yWAL4xwCHg5ZXGZRLTqyI",
    description: "Immerse yourself in the epic tale of outlaws in the American frontier.",
    price: 49.99,
    releaseDate: "October 26, 2018",
    publisher: "Rockstar Games",
    consoles: ["PlayStation 4", "Xbox One"],
  },
  {
    id: 3,
    title: "Grand Theft Auto V",
    rating: "9.6",
    imageUrl: "https://fastly.picsum.photos/id/61/3264/2448.jpg?hmac=Xi3Kq99U5tueFi0aajgUP0yWAL4xwCHg5ZXGZRLTqyI",
    description: "Join the criminal underworld and experience a massive open world.",
    price: 39.99,
    releaseDate: "September 17, 2013",
    publisher: "Rockstar Games",
    consoles: ["PlayStation 4", "Xbox One", "PC"],
  },
  {
    id: 4,
    title: "The Last of Us Part II",
    rating: "9.9",
    imageUrl: "https://fastly.picsum.photos/id/61/3264/2448.jpg?hmac=Xi3Kq99U5tueFi0aajgUP0yWAL4xwCHg5ZXGZRLTqyI",
    description: "Survive in a post-apocalyptic world in this gripping action-adventure.",
    price: 59.99,
    releaseDate: "June 19, 2020",
    publisher: "Sony Interactive Entertainment",
    consoles: ["PlayStation 4"],
  },
  {
    id: 5,
    title: "God of War",
    rating: "9.8",
    imageUrl: "https://fastly.picsum.photos/id/61/3264/2448.jpg?hmac=Xi3Kq99U5tueFi0aajgUP0yWAL4xwCHg5ZXGZRLTqyI",
    description: "Embark on a journey as Kratos, a vengeful Spartan warrior.",
    price: 49.99,
    releaseDate: "April 20, 2018",
    publisher: "Sony Interactive Entertainment",
    consoles: ["PlayStation 4"],
  },
  {
    id: 6,
    title: "Uncharted 4: A Thief's End",
    rating: "9.7",
    imageUrl: "https://fastly.picsum.photos/id/61/3264/2448.jpg?hmac=Xi3Kq99U5tueFi0aajgUP0yWAL4xwCHg5ZXGZRLTqyI",
    description: "Join Nathan Drake on his final adventure to uncover hidden treasures.",
    price: 19.99,
    releaseDate: "May 10, 2016",
    publisher: "Sony Interactive Entertainment",
    consoles: ["PlayStation 4"],
  },
  {
    id: 7,
    title: "Horizon Zero Dawn",
    rating: "9.6",
    imageUrl: "https://fastly.picsum.photos/id/61/3264/2448.jpg?hmac=Xi3Kq99U5tueFi0aajgUP0yWAL4xwCHg5ZXGZRLTqyI",
    description: "Explore a lush open world filled with robotic creatures in this action RPG.",
    price: 29.99,
    releaseDate: "February 28, 2017",
    publisher: "Sony Interactive Entertainment",
    consoles: ["PlayStation 4"],
  },
  {
    id: 8,
    title: "Minecraft",
    rating: "9.5",
    imageUrl: "https://fastly.picsum.photos/id/61/3264/2448.jpg?hmac=Xi3Kq99U5tueFi0aajgUP0yWAL4xwCHg5ZXGZRLTqyI",
    description: "Build, explore, and survive in this popular sandbox game.",
    price: 19.99,
    releaseDate: "November 18, 2011",
    publisher: "Mojang Studios",
    consoles: ["PlayStation 4", "Xbox One", "Nintendo Switch", "PC"],
  },
  {
    id: 9,
    title: "Assassin's Creed Valhalla",
    rating: "9.4",
    imageUrl: "https://example.com/assassinscreedvalhalla.jpg",
    description: "Become a legendary Viking raider in the ninth installment of the series.",
    price: 59.99,
    releaseDate: "November 10, 2020",
    publisher: "Ubisoft",
    consoles: ["PlayStation 4", "Xbox One", "PlayStation 5", "Xbox Series X", "PC"],
  },
  {
    id: 10,
    title: "Call of Duty: Warzone",
    rating: "9.3",
    imageUrl: "https://fastly.picsum.photos/id/61/3264/2448.jpg?hmac=Xi3Kq99U5tueFi0aajgUP0yWAL4xwCHg5ZXGZRLTqyI",
    description: "Engage in intense battle royale warfare and compete for victory.",
    price: 0,
    releaseDate: "March 10, 2020",
    publisher: "Activision",
    consoles: ["PlayStation 4", "Xbox One", "PlayStation 5", "Xbox Series X", "PC"],
  },
  {
    id: 11,
    title: "FIFA 21",
    rating: "9.2",
    imageUrl: "https://fastly.picsum.photos/id/61/3264/2448.jpg?hmac=Xi3Kq99U5tueFi0aajgUP0yWAL4xwCHg5ZXGZRLTqyI",
    description: "Experience the latest installment of the popular soccer simulation game.",
    price: 49.99,
    releaseDate: "October 9, 2020",
    publisher: "Electronic Arts",
    consoles: ["PlayStation 4", "Xbox One", "PlayStation 5", "Xbox Series X", "Nintendo Switch", "PC"],
  },
  {
    id: 12,
    title: "Overwatch",
    rating: "9.1",
    imageUrl: "https://fastly.picsum.photos/id/61/3264/2448.jpg?hmac=Xi3Kq99U5tueFi0aajgUP0yWAL4xwCHg5ZXGZRLTqyI",
    description: "Join a team-based multiplayer shooter and compete in thrilling matches.",
    price: 39.99,
    releaseDate: "May 24, 2016",
    publisher: "Blizzard Entertainment",
    consoles: ["PlayStation 4", "Xbox One", "Nintendo Switch", "PC"],
  },
  {
    id: 13,
    title: "Super Mario Odyssey",
    rating: "9.7",
    imageUrl: "https://fastly.picsum.photos/id/61/3264/2448.jpg?hmac=Xi3Kq99U5tueFi0aajgUP0yWAL4xwCHg5ZXGZRLTqyI",
    description: "Embark on a colorful 3D platforming adventure with Mario and Cappy.",
    price: 59.99,
    releaseDate: "October 27, 2017",
    publisher: "Nintendo",
    consoles: ["Nintendo Switch"],
  },
  {
    id: 14,
    title: "Cyberpunk 2077",
    rating: "9.0",
    imageUrl: "https://fastly.picsum.photos/id/61/3264/2448.jpg?hmac=Xi3Kq99U5tueFi0aajgUP0yWAL4xwCHg5ZXGZRLTqyI",
    description: "Enter the dystopian Night City and become a cyber-enhanced mercenary.",
    price: 29.99,
    releaseDate: "December 10, 2020",
    publisher: "CD Projekt",
    consoles: ["PlayStation 4", "Xbox One", "PlayStation 5", "Xbox Series X", "PC"],
  },
  {
    id: 15,
    title: "Final Fantasy VII Remake",
    rating: "9.5",
    imageUrl: "https://fastly.picsum.photos/id/61/3264/2448.jpg?hmac=Xi3Kq99U5tueFi0aajgUP0yWAL4xwCHg5ZXGZRLTqyI",
    description: "Relive the classic RPG with stunning visuals and revamped combat.",
    price: 49.99,
    releaseDate: "April 10, 2020",
    publisher: "Square Enix",
    consoles: ["PlayStation 4"],
  },
  {
    id: 16,
    title: "Marvel's Spider-Man",
    rating: "9.7",
    imageUrl: "https://fastly.picsum.photos/id/61/3264/2448.jpg?hmac=Xi3Kq99U5tueFi0aajgUP0yWAL4xwCHg5ZXGZRLTqyI",
    description: "Swing through New York City as the friendly neighborhood Spider-Man.",
    price: 39.99,
    releaseDate: "September 7, 2018",
    publisher: "Sony Interactive Entertainment",
    consoles: ["PlayStation 4"],
  },
  {
    id: 17,
    title: "BioShock Infinite",
    rating: "9.4",
    imageUrl: "https://fastly.picsum.photos/id/61/3264/2448.jpg?hmac=Xi3Kq99U5tueFi0aajgUP0yWAL4xwCHg5ZXGZRLTqyI",
    description: "Explore the floating city of Columbia in this captivating first-person shooter.",
    price: 19.99,
    releaseDate: "March 26, 2013",
    publisher: "2K Games",
    consoles: ["PlayStation 4", "Xbox One", "PC"],
  },
  {
    id: 18,
    title: "Tom Clancy's Rainbow Six Siege",
    rating: "9.3",
    imageUrl: "https://fastly.picsum.photos/id/61/3264/2448.jpg?hmac=Xi3Kq99U5tueFi0aajgUP0yWAL4xwCHg5ZXGZRLTqyI",
    description: "Engage in tactical multiplayer battles as part of an elite counter-terrorism unit.",
    price: 29.99,
    releaseDate: "December 1, 2015",
    publisher: "Ubisoft",
    consoles: ["PlayStation 4", "Xbox One", "PlayStation 5", "Xbox Series X", "PC"],
  },
  {
    id: 19,
    title: "Super Smash Bros. Ultimate",
    rating: "9.8",
    imageUrl: "https://fastly.picsum.photos/id/61/3264/2448.jpg?hmac=Xi3Kq99U5tueFi0aajgUP0yWAL4xwCHg5ZXGZRLTqyI",
    description: "Gather your favorite video game characters for an epic crossover fighting game.",
    price: 59.99,
    releaseDate: "December 7, 2018",
    publisher: "Nintendo",
    consoles: ["Nintendo Switch"],
  },
  {
    id: 20,
    title: "The Legend of Zelda: Breath of the Wild",
    rating: "9.9",
    imageUrl: "https://fastly.picsum.photos/id/61/3264/2448.jpg?hmac=Xi3Kq99U5tueFi0aajgUP0yWAL4xwCHg5ZXGZRLTqyI",
    description: "Discover the vast open world of Hyrule and save Princess Zelda.",
    price: 59.99,
    releaseDate: "March 3, 2017",
    publisher: "Nintendo",
    consoles: ["Nintendo Switch"],
  },
];

